export const REQUEST_OPT_PARMS = "REQUEST_OPT_PARMS";
export const SUCCESS_OPT_PARMS = "SUCCESS_OPT_PARMS";
export const FAIL_OPT_PARMS = "FAIL_OPT_PARMS";
export const RESET_OPT_PARMS = "RESET_OPT_PARMS";
