export const REQUEST_OPT_PARMS = "REQUEST_OPT_PARMS";
export const SUCCESS_OPT_PARMS = "SUCCESS_OPT_PARMS";
export const FAIL_OPT_PARMS = "FAIL_OPT_PARMS";
export const RESET_OPT_PARMS = "RESET_OPT_PARMS";

export const REQUEST_OPT_MEDIA_COMP = "REQUEST_OPT_MEDIA_COMP";
export const SUCCESS_OPT_MEDIA_COMP = "SUCCESS_OPT_MEDIA_COMP";
export const FAIL_OPT_MEDIA_COMP = "FAIL_OPT_MEDIA_COMP";
export const RESET_OPT_MEDIA_COMP = "RESET_OPT_MEDIA_COMP";
