export const SAVE_OPT_DATA = "SAVE_OPT_DATA";
export const SUCCESS_OPT_DATA = "SUCCESS_OPT_DATA";
export const FAIL_OPT_DATA = "FAIL_OPT_DATA";
export const RESET_OPT_DATA = "RESET_OPT_DATA";

export const REQUEST_OPT_PARMS = "REQUEST_OPT_PARMS";
export const SUCCESS_OPT_PARMS = "SUCCESS_OPT_PARMS";
export const FAIL_OPT_PARMS = "FAIL_OPT_PARMS";
export const RESET_OPT_PARMS = "RESET_OPT_PARMS";
