export const REQUEST_PLOT_SIMULATION = "REQUEST_PLOT_SIMULATION";
export const SUCCESS_PLOT_SIMULATION = "SUCCESS_PLOT_SIMULATION";
export const FAIL_PLOT_SIMULATION = "FAIL_PLOT_SIMULATION";
export const RESET_PLOT_SIMULATION = "RESET_PLOT_SIMULATION";
