export const REQUEST_USER_LIST = "REQUEST_USER_LIST";
export const SUCCESS_USER_LIST = "SUCCESS_USER_LIST";
export const FAIL_USER_LIST = "FAIL_USER_LIST";
export const RESET_USER_LIST = "RESET_USER_LIST";

export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";
export const FAIL_CREATE_USER = "FAIL_CREATE_USER";
export const RESET_CREATE_USER = "RESET_CREATE_USER";

export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";
export const RESET_LOGIN_USER = "RESET_LOGIN_USER";

export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER";
export const SUCCESS_UPDATE_USER = "SUCCESS_UPDATE_USER";
export const FAIL_UPDATE_USER = "FAIL_UPDATE_USER";
export const RESET_UPDATE_USER = "RESET_UPDATE_USER";
